### ISSUE TITLE
打包的大小怎么样？

### ISSUE THREAD

**Issue by TajangSec** [lengzhao/font#1]
我目前的方法是下载微软雅黑.ttf到项目文件夹内，然后设置fyne env中字体，微软雅黑的字体文件14m，打包后是原来的两倍大
如果我用你这个方法，打包后的程序是将你这个库打包进exe了吗？那么大小怎么样呢？

**Comment by lengzhao** [comment]
这只是自动配置字体文件，怎么打包、裁剪字体，我的模块不涉及，需要你自己处理。
我的模块主要是怎么自动找到系统的字体文件，自动配置。
如果你没有特殊的字体需求，可以不下载，直接使用我的模块，自动设置就行了，不需要额外打包字体。当然，如果遇到系统内没有对应语言的字体，就会显示乱码
